Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProyectoTienda.Models;
namespace ProyectoTienda.Controllers
{
    public class CarritoController : Controller
    {
        // GET: Carrito
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Agregar(int id)
        {
            ProdCarro carro = new ProdCarro();
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                Producto p = carro.find(id);
                string nam = p.nombre_producto;
                cart.Add(new Item { Producto = carro.find(id), Cantidad = 1 });
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Cantidad++;
                }
                else
                {
                    Producto p = carro.find(id);
                    string nam = p.nombre_producto;
                    cart.Add(new Item { Producto = carro.find(id), Cantidad = 1 });
                }
                Session["cart"] = cart;
            }
            return RedirectToAction("Index");
        }
        private int isExist(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Producto.Id_producto.Equals(id))
                {
                    return i;
                }

            }
            return -1;
        }
        public ActionResult Quitar(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            int index = isExist(id);
            cart.RemoveAt(index);
            Session["cart"] = cart;
            return RedirectToAction("Index");
        }
    }
}

Views/Carrito/Index.cshtml
@using ProyectoTienda.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Carro de compra</h2>

<table class="table table-bordered table-responsive table-striped"  >
    <thead>
        <tr class="info">
            <th>Opción</th>
            <th>Nombre</th>
            <th>Foto</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th>SubTotal</th>

        </tr>
    </thead>
    @foreach (Item item in (List<Item>)Session["cart"])
    {
        <tr>
            <td><a href="@Url.Action("Quitar", "Carrito", new { id=item.Producto.Id_producto})"></a></td>
            <td><img class="img-responsive" src="~/Content/Imagenes/Productos/@item.Producto.imagen_producto"/></td>
            <td>@item.Producto.precio</td>
            <td>@item.Cantidad</td>
            <td>@(item.Producto.precio*item.Cantidad)</td>
        </tr>
    }
    <tr>
        <td aling="right" colspan="6">Total</td>
        <td>
            @{ 
                List<Item> cart = (List<Item>)Session["cart"];
                var total = cart.Sum(item => item.Producto.precio * item.Cantidad);
            }
            @total
        </td>
    </tr>

</table>
<br />
<a class="btn btn-warning" href="@Url.Action("Index","Home")"> Continuar comprando</a>
<p style="float: right;color:white">
    @Html.ActionLink("Confirmar orden", "CrearOrden", "Checkout",new {area="" },new { @class="btn btn-success"})
</p>